version: '3.9'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 alphabet.asgi:application
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    links:
      - redis
    networks:
      - webnet

  worker:
    build: .
    command: celery -A alphabet worker -l info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - webnet

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - webnet

networks:
  webnet: