# Generated by Django 5.0.7 on 2024-08-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_event_end_time_alter_event_starting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='starting_time',
            field=models.DateTimeField(),
        ),
    ]
